services:
  - type: web
    name: cardgame-quest-generator
    env: node
    plan: free
    branch: main
    rootDir: CardGame_QuestGenerator
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    # envVars:
    #   - key: DATABASE_URL
    #     sync: false
